public class LC001_WrapperAdresse {

    public String id{get; set;}
    public String compteAssocie {get; set;}
    public String nom{get; set;}
    public String nomVoie{get; set;}
    public String numeroVoie{get; set;}
    public String codePostal{get; set;}
    public String commune{get; set;}
    public String attentionDe {get; set;}
    public String sousCouvertDe {get; set;}
    public String gfit {get;set;}
    
}